server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:

    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require

    username: ${SUPABASE_USER}

    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth:
  jwt:
    keystore:
      location: ${JWT_KEYSTORE_LOCATION:classpath:irms-keystore.jks}
      password: ${JWT_KEYSTORE_PASSWORD}
      alias: ${JWT_KEY_ALIAS:irms-key}
      key-password: ${JWT_KEY_PASSWORD:${JWT_KEYSTORE_PASSWORD}}

eureka:
  client:
    service-url:
      # Tell the KDS service where the Eureka server lives
      defaultZone: http://localhost:8761/eureka/