spring:
  application:
    name: service-discovery
server:
  port: 8761 # 8761 is the global standard port for Eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # I am the server, don't register me
    fetch-registry: false       # I am the server, don't fetch from anywhere else