server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          # The Menu Service will download the public key from the Auth Service to verify tokens
          jwk-set-uri: http://localhost:8081/api/auth/.well-known/jwks.json

springdoc:
  swagger-ui:
    path: /swagger-ui.html
