server:
  port: 8089
spring:
  application:
    name: kds-service

  # MongoDB Atlas template
  # Replace <username>, <password>, and <cluster-url>
  mongodb:
    uri: ${mongo_uri:mongodb://localhost:27017}
    database: kds_service

  # CloudAMQP template (RabbitMQ)
  # Use values from your CloudAMQP instance
  rabbitmq:
    host: ${cloudamqp_host}
    port: 5672
    username: ${cloudamqp_username}
    password: ${cloudamqp_password}
    virtual-host: ${cloudamqp_vhost}
    ssl:
      enabled: false

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8081/api/auth/.well-known/jwks.json

app:
  rabbitmq:
    exchange: restaurant.events
    order-created-queue: kds.order.created
    order-created-routing-key: order.created
    order-status-updated-routing-key: order.status.updated

  kds:
    station-id: KDS-Station-HotLine
  security:
    # Notice we use the Eureka name "auth-service" instead of localhost:8081!
    jwk-set-uri: http://auth-service/api/auth/.well-known/jwks.json

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}
    non-secure-port-enabled: ${EUREKA_NON_SECURE_PORT_ENABLED:true}
    secure-port-enabled: ${EUREKA_SECURE_PORT_ENABLED:false}
    secure-port: ${EUREKA_SECURE_PORT:443}
    home-page-url: ${EUREKA_HOME_PAGE_URL:http://${eureka.instance.hostname}:${server.port}/}
    status-page-url: ${EUREKA_STATUS_PAGE_URL:${eureka.instance.home-page-url}}
    health-check-url: ${EUREKA_HEALTH_CHECK_URL:${eureka.instance.home-page-url}}
  client:
    service-url:
      # Tell the KDS service where the Eureka server lives
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
