spring.application.name=kds-service

# MongoDB
spring.data.mongodb.database=kds_service

# RabbitMQ contract
app.rabbitmq.exchange=restaurant.events
app.rabbitmq.order-created-queue=kds.order.created
app.rabbitmq.order-created-routing-key=order.created
app.rabbitmq.order-status-updated-routing-key=order.status.updated

# Event metadata
app.kds.station-id=KDS-Station-HotLine
